"""
LangGraph State Schema

Defines the state object that flows through the agent graph.
Each node (agent) can read from and write to this state.
"""

from typing import TypedDict, Optional, Annotated
from operator import add


class RAGState(TypedDict):
    """
    State object for the RAG workflow.

    This state flows through all nodes in the graph.
    Each agent can read and modify the state.
    """

    # User query
    query: str
    """Original user query"""

    # Query processing
    expanded_query: Optional[str]
    """Query expanded by retriever for better search"""

    ambiguities: Optional[list[str]]
    """List of ambiguities detected in the query"""

    clarifications: Optional[dict]
    """User-provided clarifications for ambiguous terms"""

    needs_clarification: bool
    """Flag indicating if clarification is needed"""

    # Retrieval
    retrieved_docs: Annotated[list[dict], add]
    """
    Documents retrieved from vector store.
    Uses 'add' operator to append chunks during streaming.
    """

    retrieval_metadata: Optional[dict]
    """Metadata about retrieval (e.g., total_docs, sources)"""

    # Grounding
    grounded_docs: Optional[list[dict]]
    """Documents after grounding (normalized, deduplicated, with citations)"""

    # Answer generation
    answer: Optional[str]
    """Final answer generated by answerer agent"""

    # Verification
    verification_result: Optional[dict]
    """
    Results from verifier agent.
    Format: {
        verified: bool,
        unsupported_claims: list[str],
        missing_info: list[str]
    }
    """

    needs_more_retrieval: bool
    """Flag if verifier requests additional retrieval"""

    # Metadata and tracking
    metadata: dict
    """
    Additional metadata for tracking.
    e.g., timestamps, agent traces, error messages
    """


# TODO: Implement state initialization helper
# TODO: Implement state validation functions
# TODO: Add state serialization for persistence
